version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app/watchtower:/watchtower/app/watchtower
      - ~/.certs/github/bot_key.pem:/key.pem
    ports:
      - 8000:8000
    command: ['bash', '-c', 'gunicorn --bind :8000 --workers 4 --reload wsgi:application']
    depends_on:
      - database
    networks:
      - watchtower_network

  test:
    build:
      context: .
      dockerfile: Dockerfile.pytest
    profiles: ["test"]

  initializer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app/watchtower:/watchtower/app/watchtower
      - ~/.certs/github/bot_key.pem:/key.pem
    command: ['bash', '-c', 'python3 manage.py migrate && python3 manage.py runscript initializer']
    depends_on:
      - database
    networks:
      - watchtower_network

  database:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=watchtower
    ports:
      - 5432:5432
    networks:
      - watchtower_network

  smee:
    image: deltaprojects/smee-client
    command: ["-u", "https://smee.io/wjfg5GJdRT6xc", "-t", "http://app:8000/webhook/"]
    networks:
      - watchtower_network
    logging:
      driver: none
    read_only: true

  rabbit:
    build:
      context: Rabbit
      dockerfile: Dockerfile.rabbit.local
    hostname: rabbit
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - watchtower_network

  flower:
    image: mher/flower:latest
    environment:
      - CELERY_BROKER_URL=amqp://admin:bigpassword@rabbit:5672//
      - FLOWER_PORT=5555
      - FLOWER_PURGE_OFFLINE_WORKERS=10
    read_only: true
    ports:
      - 5555:5555
    depends_on:
      - rabbit
    profiles:
      - "debug"
    networks:
      - watchtower_network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A watchtower_service worker -l INFO --uid 1
    env_file:
      - .env
    volumes:
      - ./app/watchtower:/watchtower/app/watchtower
      - ~/.certs/github/bot_key.pem:/key.pem
    depends_on:
      - rabbit
      - database
    networks:
      - watchtower_network


volumes:
  postgres_data:
  rabbitmq:

networks:
  watchtower_network: