version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app/watchtower:/watchtower/app/watchtower
    ports:
      - 8000:8000
    command: ['bash', '-c', 'gunicorn --bind :8000 --workers 4 --reload watchtower.wsgi:application']
    depends_on:
      - database
    networks:
      - project_network

  initializer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app/watchtower:/watchtower/app/watchtower
    command: ['bash', '-c', 'python3 manage.py migrate']
    depends_on:
      - database
    networks:
      - project_network

  database:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=watchtower
    ports:
      - 5432:5432
    networks:
      - project_network

volumes:
  postgres_data:

networks:
  project_network: