# Generated by Django 4.0.6 on 2022-08-25 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(db_index=True, max_length=256)),
                ('installation_count', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('owner_type', models.CharField(choices=[('user', 'User'), ('org', 'Organization')], default='org', max_length=4)),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateField()),
            ],
            options={
                'unique_together': {('owner_id', 'owner_type')},
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.IntegerField(primary_key=True, serialize=False)),
                ('organization_login', models.CharField(db_index=True, max_length=256)),
                ('organization_name', models.CharField(max_length=256)),
                ('organization_type', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=2048, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateField()),
                ('company', models.CharField(max_length=128, null=True)),
                ('avatar_url', models.URLField(null=True)),
                ('default_repository_permission', models.CharField(max_length=32)),
                ('disk_usage', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.IntegerField()),
                ('target_id', models.IntegerField()),
                ('target_type', models.CharField(choices=[('org', 'Organization'), ('repo', 'Repository')], default='org', max_length=4)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchtower_service.app')),
            ],
            options={
                'unique_together': {('target_id', 'target_type')},
            },
        ),
    ]
