# Generated by Django 4.1.1 on 2022-09-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchtower_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubuser",
            name="name",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
