# Generated by Django 4.0.6 on 2022-07-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchtower_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_json', models.JSONField()),
            ],
        ),
    ]
