# Generated by Django 4.0.6 on 2022-08-31 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "watchtower_service",
            "0002_alter_app_installation_count_alter_app_name_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="installation",
            old_name="app_id",
            new_name="app",
        ),
    ]
