# Generated by Django 4.1 on 2022-09-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchtower_service", "0004_remove_installation_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="owner_id",
            field=models.IntegerField(null=True),
        ),
    ]
