# Generated by Django 4.1 on 2022-09-06 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchtower_service", "0005_alter_repository_owner_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="app",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="installation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="repository",
            unique_together=set(),
        ),
    ]
