# Generated by Django 4.1 on 2022-09-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchtower_service", "0006_alter_app_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="installation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="repository",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
