# Generated by Django 4.1.1 on 2022-09-14 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "watchtower_service",
            "0007_alter_app_updated_at_alter_installation_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GithubUser",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("login", models.CharField(max_length=256)),
                ("name", models.CharField(max_length=256, null=True)),
                ("bio", models.CharField(max_length=8192, null=True)),
                ("company", models.CharField(max_length=128, null=True)),
                ("account_created", models.DateTimeField()),
                ("account_updated", models.DateTimeField()),
                ("disk_usage", models.IntegerField(null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("plan", models.CharField(max_length=32, null=True)),
                ("role", models.CharField(max_length=64, null=True)),
                ("site_admin", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_organization_admin", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="watchtower_service.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="watchtower_service.githubuser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="githubuser",
            name="organizations",
            field=models.ManyToManyField(
                related_name="members",
                through="watchtower_service.OrganizationMember",
                to="watchtower_service.organization",
            ),
        ),
    ]
